### ISSUE TITLE
"can't concat bytes to str" error

### ISSUE THREAD

**Issue by nazikus** [Evolution0/bandcamp-dl#95] opened 2017-01-12 20:45 UTC
**Platform**: Windows 8.1 x64, Python 3.5.2 
**Bandcamp URL**:  https://marquishawkes.bandcamp.com/album/social-housing

`--verbose` key is not working in 0.0.6 version (and `-v` is for version).

**Output**:
```

d:\>bandcamp-dl.exe --version
bandcamp-dl 0.0.6-01

d:\>python --version
Python 3.5.2

d:\>bandcamp-dl.exe --verbose https://marquishawkes.bandcamp.com/album/social-housing
Usage:
  bandcamp-dl.py <url>
  bandcamp-dl.py [--template=<template>] [--base-dir=<dir>]
                 [--full-album]
                 (<url> | --artist=<artist> --album=<album>)
                 [--overwrite]
                 [--no-art]
  bandcamp-dl.py (-h | --help)
  bandcamp-dl.py (--version)

d:\>bandcamp-dl.exe https://marquishawkes.bandcamp.com/album/social-housing
WARNING: Couldn't write lextab module <module 'slimit.lextab' from 'c:\\dev\\python35\\lib\\site-packages\\slimit\\lextab.py'>. Won't overwrite existing lextab module 
WARNING: yacc table file version is out of date
WARNING: Token 'CONST' defined, but not used
WARNING: Token 'CLASS' defined, but not used
WARNING: Token 'SUPER' defined, but not used
WARNING: Token 'EXPORT' defined, but not used
WARNING: Token 'LINE_COMMENT' defined, but not used
WARNING: Token 'LINE_TERMINATOR' defined, but not used
WARNING: Token 'IMPORT' defined, but not used
WARNING: Token 'EXTENDS' defined, but not used
WARNING: Token 'BLOCK_COMMENT' defined, but not used
WARNING: Token 'ENUM' defined, but not used
WARNING: There are 10 unused tokens
WARNING: Couldn't create <module 'slimit.yacctab' from 'c:\\dev\\python35\\lib\\site-packages\\slimit\\yacctab.py'>. Won't overwrite existing tabmodule
WARNING: Couldn't write lextab module <module 'slimit.lextab' from 'c:\\dev\\python35\\lib\\site-packages\\slimit\\lextab.py'>. Won't overwrite existing lextab module
WARNING: yacc table file version is out of date
WARNING: Token 'CONST' defined, but not used
WARNING: Token 'CLASS' defined, but not used
WARNING: Token 'SUPER' defined, but not used
WARNING: Token 'EXPORT' defined, but not used
WARNING: Token 'LINE_COMMENT' defined, but not used
WARNING: Token 'LINE_TERMINATOR' defined, but not used
WARNING: Token 'IMPORT' defined, but not used
WARNING: Token 'EXTENDS' defined, but not used
WARNING: Token 'BLOCK_COMMENT' defined, but not used
WARNING: Token 'ENUM' defined, but not used
WARNING: There are 10 unused tokens
WARNING: Couldn't create <module 'slimit.yacctab' from 'c:\\dev\\python35\\lib\\site-packages\\slimit\\yacctab.py'>. Won't overwrite existing tabmodule

Starting download process.
Accessing track 1 of 12
can't concat bytes to str
Downloading failed..

d:\>
```

**Comment by Evolution0** [comment] 2017-01-13 00:11
I know what the issue is and its easy to fix, shouldn't take long.

**Comment by Evolution0** [comment] 2017-01-13 00:20
Alright do: `pip install --upgrade bandcamp-downloader`

Should work correctly now.

**Comment by Evolution0** [comment] 2017-01-13 00:37
Did a multiple release, I suggest using 0.0.7-01, just upgrade and it will take care of itself.

**Comment by nazikus** [comment] 2017-01-13 08:50
"concat bytes" error is gone, but now I cannot playback downloaded mp3s, all the files are suspiciously similar in size and too small.
![image](https://cloud.githubusercontent.com/assets/2558905/21923593/9c35b1b0-d97d-11e6-9667-ad0563bbb0b2.png)

[downloaded files](https://dl.dropboxusercontent.com/u/553423/Service/marquis-hawkes.zip)

VLC output:
```
es error: cannot peek
es error: cannot peek
es error: cannot peek
es error: cannot peek
es error: cannot peek
ps error: cannot peek
mjpeg error: cannot peek
mpgv error: cannot peek
ps error: cannot peek
core error: no suitable demux module for `file/any:///C:/Users/naz/Music/.Current/marquis-hawkes/social-housing/01%20-%20ode-to-a-broken-heart.mp3'
```

**Comment by Evolution0** [comment] 2017-01-13 17:43
Indeed, the file length doesn't match up with the content-length header like it should.. and since it doesn't attempt to overwrite I at least know where to look.

**Comment by Evolution0** [comment] 2017-01-13 18:44
Something isn't quite right, I haven't modified the actual download process in some time and even with chunk downloading off the files are not the correct size. Its happening on all URLs as well..

None of the dependencies have changed very much either so its most likely not that.

**Comment by Evolution0** [comment] 2017-01-13 18:51
Seems to be an issue with the encoding process, I must have messed up or something when adding the new tmp filename/rename delete bit.

**Comment by Evolution0** [comment] 2017-01-13 18:59
Found the issue, I didn't know Mutagen well enough, attempting to save the current encoding process was a bad move, I guess it only holds the chunk that its modifying and not the whole file. Will be fixed in a bit. Sorry for the trouble.

**Comment by Evolution0** [comment] 2017-01-13 19:16
Keep in mind PyPI is having issues right now so it may be a bit till a new release is up to upgrade, I will however tag a release and put the wheel up which can be installed following the instructions in the readme.

**Closed as completed** 2017-01-13 19:15 UTC
Labels: bug

**Comment by nazikus** [comment] 2017-01-14 10:55
Great. Thanks for prompt response, and all the comments, I'm planning to use mutagen myself, good to know some pitfalls beforehand.
