### ISSUE TITLE
Support user collections as a multi-track source

### ISSUE THREAD

**Issue by paradoxfound** [Evolution0/bandcamp-dl#158] opened 2019-03-22 16:37 UTC
I keep getting this error for some reason. I am running Parrot OS. 

```
Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/bandcamp_dl/__main__.py", line 93, in main
    album = bandcamp.parse(url, True, arguments['--embed-lyrics'], arguments['--debug'])
  File "/usr/local/lib/python3.7/dist-packages/bandcamp_dl/bandcamp.py", line 40, in parse
    bandcamp_json = BandcampJSON(self.soup, debugging).generate()
  File "/usr/local/lib/python3.7/dist-packages/bandcamp_dl/bandcampjson.py", line 25, in generate
    self.js_to_json()
  File "/usr/local/lib/python3.7/dist-packages/bandcamp_dl/bandcampjson.py", line 50, in js_to_json
    self.get_js()
  File "/usr/local/lib/python3.7/dist-packages/bandcamp_dl/bandcampjson.py", line 37, in get_js
    self.js_data = self.body.find("script", {"src": False}, text=re.compile(self.target)).string
AttributeError: 'NoneType' object has no attribute 'string'
```

**Comment by Evolution0** [comment] 2019-03-25 01:19
Usually this error comes up when the script object wasn't found on the page. This can either be due to the page not existing or some change to bandcamp that prevents it from being retrieved.

I've got a template for issues for a reason, whats the url? (or artist/album/track)

**Comment by paradoxfound** [comment] 2019-03-25 14:50
https://bandcamp.com/theonlysun81

**Comment by paradoxfound** [comment] 2019-03-26 17:16
would the problem have to do with the fact that this isn't an artist page, but my personal collection

**Comment by Evolution0** [comment] 2019-03-30 06:27
Yeah the page is composed differently, bandcamp-dl grabs the tracks from the source the embedded player uses on album/track pages.

Currently it doesn't support discographies, artist pages, and collections.

I actually wasn't aware collections was a thing as with as ironic as it sounds I don't even use bandcamp really. I'll tag it as a possible enhancement though.

**Comment by Evolution0** [comment] 2019-08-07 18:26
Currently WIP, will be in ~~0.0.9.~~ 1.0.0

Duplicate of #150 technically so closing this one.

**Closed as completed** 2021-01-12 02:53 UTC
Labels: enhancement
