### ISSUE TITLE
Make it work on track hyperlinks

### ISSUE THREAD

**Issue by nuentes** [Evolution0/bandcamp-dl#57] opened 2016-05-15 19:57 UTC
I have a couple stand-alone tracks I want to download, which are not available on any albums.  When I use the /track/ hyperlink, I get traceback errors, because album title is not defined.  Any chance this can be expanded so if the album title is not defined, it uses the track title as the album title with "(single)" appended to the end?

I think it would also be useful if full discography was an option - just enter the base bandcamp hyperlink, and it will download all releases for that artist

I'm having trouble confirming I'm using the latest version.  I have 1.0 installed, but I can't find what the current version on here is.

**Comment by Evolution0** [comment] 2016-12-13 22:05
Could you provide some example likes for testing?

**Comment by Evolution0** [comment] 2016-12-19 19:04
From what I can see track links are almost the same as album links, you still have access to the embed data.

Now I don't know if this differs from actual singles but it looks easily doable.

We just need some checking implemented so it doesn't break on anything relating to album titles.

**Comment by Evolution0** [comment] 2016-12-26 23:40
Hm, it seems to work on both track links and albums with a single track just fine. However the overwrite detection seems to not work.. thats another matter entirely.

Sounds like you ran into some kind of special case where an individual track was released outside of an EP, as I can't reproduce this without a similar link.. I'm closing it.

**Closed as completed by Evolution0** 2016-12-26 23:40 UTC
Labels: enhancement
