### ISSUE TITLE
crash on KeyError: 'album_title'?

### ISSUE THREAD

**Issue by PedroLopes** [Evolution0/bandcamp-dl#48] opened 2016-03-10 13:45 UTC
Hey @iheanyi, just to let you know that when I try this:
`bandcamp-dl https://gregorylenczycki.bandcamp.com/track/str-qrt-no-one`

I get:

```
Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 9, in <module>
    load_entry_point('bandcamp-downloader==0.0.3', 'console_scripts', 'bandcamp-dl')()
  File "/Library/Python/2.7/site-packages/bandcamp_dl/bandcamp_dl.py", line 55, in main
    album = bandcamp.parse(url)
  File "/Library/Python/2.7/site-packages/bandcamp_dl/Bandcamp.py", line 28, in parse
    album_meta = self.extract_album_meta_data(r)
  File "/Library/Python/2.7/site-packages/bandcamp_dl/Bandcamp.py", line 76, in extract_album_meta_data
    album['title'] = embedData['EmbedData']['album_title']
KeyError: 'album_title'
```

This was done with the latest version, i even installed fresh:

```
pedro:bandcamp_dl pedro$ sudo pip install bandcamp-downloader
Downloading/unpacking bandcamp-downloader
  Downloading bandcamp-downloader-0.0.3.tar.gz
  Running setup.py (path:/private/tmp/pip_build_root/bandcamp-downloader/setup.py) egg_info for package bandcamp-downloader

    warning: no files found matching '*.rst'
    warning: no previously-included files found matching '*.mp3'
    warning: no previously-included files found matching '.gitignore'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.DS_STORE' found anywhere in distribution
Requirement already satisfied (use --upgrade to upgrade): wgetter>=0.6 in /Library/Python/2.7/site-packages (from bandcamp-downloader)
Requirement already satisfied (use --upgrade to upgrade): slimit>=0.8.1 in /Library/Python/2.7/site-packages (from bandcamp-downloader)
Requirement already satisfied (use --upgrade to upgrade): ply==3.4 in /Library/Python/2.7/site-packages (from bandcamp-downloader)
Requirement already satisfied (use --upgrade to upgrade): mutagen>=1.31 in /Library/Python/2.7/site-packages (from bandcamp-downloader)
Requirement already satisfied (use --upgrade to upgrade): lxml>=3.5.0 in /Library/Python/2.7/site-packages (from bandcamp-downloader)
Requirement already satisfied (use --upgrade to upgrade): docopt>=0.6.2 in /Library/Python/2.7/site-packages (from bandcamp-downloader)
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4>=4.4.1 in /Library/Python/2.7/site-packages (from bandcamp-downloader)
Requirement already satisfied (use --upgrade to upgrade): slugify==0.0.1 in /Library/Python/2.7/site-packages (from bandcamp-downloader)
Installing collected packages: bandcamp-downloader
  Running setup.py install for bandcamp-downloader

    warning: no files found matching '*.rst'
    warning: no previously-included files found matching '*.mp3'
    warning: no previously-included files found matching '.gitignore'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.DS_STORE' found anywhere in distribution
    Installing bandcamp-dl script to /usr/local/bin
Successfully installed bandcamp-downloader
Cleaning up...
```

However when I ran the version on my fork (https://github.com/PedroLopes/bandcamp-dl)  which I don't see what has that could handle that problem, it does work fine:

``````
python bandcamp_dl.py https://gregorylenczycki.bandcamp.com/track/str-qrt-no-one
Starting download process.
Accessing track 1 of 1
```_
``````

**Comment by berrythesoftwarecodeprogrammar** [comment] 2016-03-11 13:09
dont install it from pip. clone this repo

**Comment by PedroLopes** [comment] 2016-03-11 13:27
Hey @berrythesoftwarecodeprogrammar that sounds like a possibility but I think most people will go with a pip installation (or they preferred package manager) over cloning the repo. So the pip version differs from the repo?

**Comment by berrythesoftwarecodeprogrammar** [comment] 2016-03-11 13:29
yep see https://github.com/iheanyi/bandcamp-dl/issues/46

**Comment by PedroLopes** [comment] 2016-03-11 13:44
Sounds like it. Perhaps it should, but that's a matter for another issue :+1: so I'm closing this one.

**Comment by berrythesoftwarecodeprogrammar** [comment] 2016-03-11 22:43
yeah i dont know how python packages work but i guess @iheanyi  needs to update them

**Comment by iheanyi** [comment] 2016-03-11 22:45
Hmmmm, maybe the album_title is missing. Lemme look into this after I get back from my vacation, all right? 

EDIT: Seems like I forgot to publish a new version. Heh.

**Comment by Evolution0** [comment] 2016-12-11 20:15
Bug still exists, going to take a look at it.

**Comment by Evolution0** [comment] 2016-12-19 19:23
I'm an idiot, only now noticed this is a track link.

In that case its a duplicate of a previous issue, closing.

**Closed as completed by Evolution0** 2016-12-19 19:23 UTC
Labels: bug
