### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by TipperDreaMT** [Evolution0/bandcamp-dl#210] opened 2023-05-31 05:52 UTC
After running setup.py in powershell using python 3.10. Chardet cannot be found
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

Installed c:\python310\lib\site-packages\bandcamp_downloader-0.0.15-py3.10.egg
Processing dependencies for bandcamp-downloader==0.0.15
Searching for chardet
Reading https://pypi.org/simple/chardet/
Download error on https://pypi.org/simple/chardet/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007) -- Some packages may not be found!
Couldn't find index page for 'chardet' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007) -- Some packages may not be found!
No local packages or working download links found for chardet
error: Could not find suitable distribution for Requirement.parse('chardet')

 - OS: [Windows 11]
 - Python Version [3.10]

**Comment by Evolution0** [comment] 2023-06-01 02:19
If you installed Python via the Microsoft Store I recommend you remove it and install it [the right way](https://www.python.org/downloads/).

I've seen this error come up before and its usually caused by a broken Python installation.

**Comment by TipperDreaMT** [comment] 2023-06-01 02:43
No, I used the python website, which python version is it confirmed to work
with

**Comment by Evolution0** [comment] 2023-06-02 22:45
Python 3.4 to the latest. 

Are you behind a firewall that would be blocking pypi.org, python.pypi.org, or files.pythonhosted.org?

Try: `pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org pip setuptools`

**Comment by Evolution0** [comment] 2024-07-01 21:41
Windows/user issue rather than a bandcamp-dl issue, closing.

**Closed as completed by Evolution0** 2024-07-01 21:41 UTC
Labels: bug
